### ISSUE TITLE
Complementary color is not correct

### ISSUE THREAD

**Issue by stanlyonhack** [evanleck/kodachroma#1]
Hi @evanleck,

When I try to get the complementary value of a color, I get a color that from my point of view is not correct. The image below shows the colors I am working with.

![colors](https://user-images.githubusercontent.com/55066385/146947815-df142b12-56b5-43dc-9acf-49d06016a236.png)

The following code I have used to obtain the complementary value of the color #ffd000
```ruby
require 'kodachroma'
puts Kodachroma.paint('#ffd000').complement

#OUTPUT > #002fff 
```

However the complementary of #ffd000 is #002fff an unwanted color for me.

Best regards,
Stan.

**Comment by evanleck** [comment]
Hey Stan, from what I can tell we're doing the right thing here. The code for the `#complement` method is below and it just rotates the hue 180 from where it is. What URL are you using to generate that other complementary color? I tried the same thing on https://www.canva.com/colors/color-wheel/ and got `#002fff`.

```ruby
# Returns the complementary color.
#
# @example
#   'red'.paint.complement #=> cyan
#
# @return [Color] the complementary color
def complement
  hsl = self.hsl
  hsl.h = (hsl.h + 180) % 360
  self.class.new(hsl, @format)
end
```

**Comment by stanlyonhack** [comment]
Hi @evanleck,

The problem is that I am working with colors in a RYB color space and not RGB.

Can't set RYB color model? if not, it is something that I must implement.

Best regards,
Stan.

**Comment by evanleck** [comment]
@stanlyonhack I don't believe the RYB color model is supported, no. PRs welcome, though!
