### ISSUE TITLE
Invalid HSL (and probably HSV) conversion when component is 1%

### ISSUE THREAD

**Issue by DEfusion** [evanleck/kodachroma#2]
If you give kodachroma a HSL string with either the saturation or lightness of `1%` it converts it incorrectly.

Example:

```
Kodachroma.paint('hsl(60, 1%, 34%)').to_rgb
# =>  "rgb(173, 173, 0)"
```

Expected:

```
Kodachroma.paint('hsl(60, 1%, 34%)').to_rgb
# =>  "rgb(88, 88, 86)"
```

I checked tinycolor and that does work as expected.

**Comment by evanleck** [comment]
I just released v1.0.2 which includes your fix. https://rubygems.org/gems/kodachroma/versions/1.0.2
